# .github/actions/setup-and-build/action.yml
name: 'Setup and Build'
description: 'Sets up Java, Node.js, installs dependencies, and builds the project'
inputs:
  node-version:
    description: 'Node.js version to setup'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        architecture: x64

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install Dependency
      run: npm ci

    - name: Test generator
      run: cd generator; mvn package; cd ..

    - name: Generate code
      run: python3 generate-code.py
